# Generated by Django 2.2.11 on 2020-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='delete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
